name: 📶 Coverage

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: "0"
      RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
      RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
      CARGO_TARGET_DIR: target/coverage

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Rust nightly
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: nightly
          override: true

      # Install grcov
      - name: Install grcov
        run: sudo apt-get install grcov

      # Configure cache for Cargo
      - name: Cache Cargo registry, index
        uses: actions/cache@v4
        id: cache-cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
            ~/.cargo/git
          key: linux-${{ steps.toolchain.outputs.rustc_hash }}-rust-cov-${{ hashFiles('**/Cargo.lock') }}

      # Run tests with all features and coverage flags
      - name: Test (cargo test)
        run: cargo test --workspace --all-features

      # Generate coverage report with grcov
      - name: Generate Coverage Report
        run: |
          grcov . \
          --binary-path ./target/coverage/debug/ \
          -s . \
          -t lcov \
          --branch \
          --ignore-not-existing \
          -o lcov.info

      # Upload to Codecov.io
      - name: Upload to Codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
